# fly.toml file generated for leather-mysql on 2023-03-18T10:56:05+02:00

app = "leather-mysql"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "waw"

[build]
  image = "mysql:8"

[env]
  MYSQL_DATABASE = "leather_accessories_schema"
  MYSQL_USER = "squser"

[experimental]
  cmd = [
    "--default-authentication-plugin", "mysql_native_password",
    "--datadir", "/data/mysql",
    "--performance-schema=OFF",
    "--innodb-buffer-pool-size", "64M"
  ]

[mounts]
  destination = "/data"
  source = "mysqldata"
